### ISSUE TITLE
error:04099079:rsa routines:RSA_padding_check_PKCS1_OAEP_mgf1:oaep decoding error

### ISSUE THREAD

**Issue by anujsinghwd** [weblab-technology/rsa-aes-client-server-encryption-nodejs-example#1]
```jsx
    return method(toBuf(key), buffer, padding, passphrase);
           ^

Error: error:04099079:rsa routines:RSA_padding_check_PKCS1_OAEP_mgf1:oaep decoding error
    at Object.privateDecrypt (internal/crypto/cipher.js:43:12)
    at Object.rsaWrapper.decrypt (/Users/anujsingh/code-play/Node-Apps/rsa-aes-client-server-encryption-nodejs-example/components/rsa-wrapper.js:43:22)
    at Socket.<anonymous> (/Users/anujsingh/code-play/Node-Apps/rsa-aes-client-server-encryption-nodejs-example/index.js:24:59)
    at Socket.emit (events.js:182:13)
    at /Users/anujsingh/code-play/Node-Apps/rsa-aes-client-server-encryption-nodejs-example/node_modules/socket.io/lib/socket.js:503:12
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

**Comment by pradoo** [comment]
I was seeing this issue also after generating new keys. Try reverting your changes in the `./keys` directory, or make sure to replace them in `./static/index.html`. Hope this helps!

**Comment by knyga** [comment]
@pradoo thanks for pull request
